name: Update Sitemap

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-sitemap:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Run update script
      env:
        WEBFLOW_API_KEY: ${{ secrets.WEBFLOW_API_KEY }}
      run: python update_sitemap.py
    
    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add sitemap.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update sitemap.json" && git push)